name: CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    # Only run for PRs from the same repository (not forks) or from specific actor
    if: github.actor == 'guglio' || github.event.pull_request.head.repo.full_name == github.repository

jobs:
  test-and-deploy:
    name: Test and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        # with:
        #   node-version: 20

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        run: npm ci

      - name: Run Lint
        run: npm run lint

      - name: Run Tests
        run: npm test

      - name: Build
        run: npm run build

      - name: Upload to FTP
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: sebastianpopp/ftp-action@releases/v2
        with:
          host: ${{ secrets.FTP_SERVER }}
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          localDir: 'dist'
          remoteDir: '/wordle.guglielmo-turco.com/public_html'
          options: '--delete'
